version: '3.7'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: tu_contraseña_mysql
      MYSQL_DATABASE: tu_base_de_datos
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: