---
- hosts: web
  become: true
  tasks:

        
- name: Instalar Docker
      package:
        name: docker
        state: present

    - name: Iniciar servicio Docker
      service:
        name: docker
        state: started
        enabled: yes

